### ISSUE TITLE
Docker - Problem Running dataserver command separately - "connect: no route to host"

### ISSUE THREAD

**Issue by Spuddyminer** [tellor-io/telliot#314] opened 2020-12-07 12:07 UTC
When running the dataserver separately from the miner, there seems to be a problem communicating with APIs in indexes.  _Could be a problem with my setup._

Example commands:
`docker run --net=host  -v $(pwd)/configs:/configs tellor/telliot:master --config=configs/config_server.json dataserver`
`docker run --net=host  -v $(pwd)/configs:/configs tellor/telliot:master --config=configs/config_miner15.json mine -r`

The errors read something like: "WARN...Problem fetching data from:https://api.coingecko...Connect:no route to host...". This seems to effect every api connection for the dataserver.

When not using docker, would normally run: (each in a separate tab)

`./tellor --config=configs/config_server.json dataserver`
`./tellor --config=configs/config_miner1.json mine-r`
`./tellor --config=configs/config_miner2.json mine-r`
and so on.

**Comment by hhio618** [comment] 2021-01-17 20:35
I couldn't reproduce this! could be a host/docker setup problem!

**Comment by themandalore** [comment] 2021-02-02 15:30
Closing since we can't reproduce, we'll deal with Spuddy's personal issues seperately

**Closed by themandalore** 2021-02-02 15:30 UTC
Labels: priority: .high, type: bug
